################################### tell Emacs this is a -*- makefile-gmake -*-
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (c) 2020-2025, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
###############################################################################

ifdef NV_COMPONENT_FLAG_SHARED_LIBRARY_SECTION
include $(NV_BUILD_START_COMPONENT)

NV_COMPONENT_STRICT_WARNINGS_qnx_64 := 1

NV_COMPONENT_NAME		:= nvgpu-drv-igpu
include $(NV_COMPONENT_DIR)/../Makefile.common.tmk
include $(NV_BUILD_SHARED_LIBRARY)
endif

# Local Variables:
# indent-tabs-mode: t
# tab-width: 8
# End:
# vi: set tabstop=8 noexpandtab:
